#   https://www.youtube.com/watch?v=yYLQczw2bMo&t=91s

- id: table_slider
  alias: Table Slider
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: input_number.dimmer
  action:
    service: "mqtt.publish"
    data_template:
      topic: "smartthings/Table/level"
      retain: "true"
      payload: '{{states("input_number.dimmer") | round(0)}}'

- id: hass_theme
  alias: hass_theme
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_select.hass_theme
  action:
    - service: frontend.set_theme
      data_template:
        name: "{{ states.input_select.hass_theme.state }}"

- id: initial_theme
  alias: 'Set theme at startup'
  initial_state: 'on'
  trigger:
   - platform: homeassistant
     event: start
  action:
    service: frontend.set_theme
    data:
      name: default

