- platform: mjpeg
  name: "raspi2A_workshop"
  mjpeg_url: http://192.168.111.64:56000/mjpeg

- platform: mjpeg
  name: "raspi2B_sump"
  mjpeg_url: http://192.168.111.65:56000/mjpeg

- platform: mjpeg
  name: "raspi3A_office"
  mjpeg_url: http://192.168.111.67:56000/mjpeg

- platform: mjpeg
  name: "raspi3B_demo"
  mjpeg_url: http://192.168.111.70:56000/mjpeg

- platform: mjpeg
  name: "front_yard"
  mjpeg_url: http://192.168.111.90/img/video.mjpeg
