homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 42.330964
  longitude: -87.993612
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
introduction:

zeroconf:

lovelace:

input_select: !include input_select.yaml

http:
  base_url: https://hass.hoppel.us:54102
#  api_password: !secret ha_password 

system_health:

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes/

#nest:       !include secrets.yaml
nest: 
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

# Enables configuration UI
config:

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
#updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:
#  ignore:
#    - plex_mediaserver
#    - google_cast
#    - roku
#  enable:
#
#cast: !include cast.yaml

#    
# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

#device_tracker: !include device_trackers.yaml
googlehome: !include googlehome.yaml

#device_tracker:
#  - platform: google_maps
#    username: !secret google_user
#    password: !secret google_password

person:
  - name: rick
    id: rick
    device_trackers:
      - device_tracker.192_168_111_237_d0_13_fd_f1_a4_cb
      - device_tracker.192_168_111_238_d0_13_fd_f1_a4_cb
      - device_tracker.192_168_111_239_d0_13_fd_f1_a4_cb
      - device_tracker.192_168_111_240_d0_13_fd_f1_a4_cb
      - device_tracker.192_168_111_241_d0_13_fd_f1_a4_cb
      - device_tracker.192_168_111_242_d0_13_fd_f1_a4_cb
   
# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

#recorder
recorder: !include recorder.yaml


# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Sensor
#sensor: 
  # Weather prediction
#  - platform: yr

# Text to speech
tts:
  - platform: google

# Cloud
#cloud:

mqtt:
  broker:  192.168.111.250
  discovery: true
  #  discovery_prefix: smartthings
  #  discovery_prefix: homeassistant

input_number:
  dimmer:
    name: Dimmer Brightness
    initial: 1
    min: 1
    max: 100
    step: 5

# !include_dir_list will return the content of a directory as a list with each file content being an entry in the list.
# !include_dir_named will return the content of a directory as a dictionary which maps filename => content of file.
# !include_dir_merge_list will return the content of a directory as a list by merging all fsmartiles (which should contain a list) into 1 big list.
# !include_dir_merge_named will return the content of a directory as a dictionary by loading each file and merging it into 1 big dictionary.

weather: 
  - platform: darksky
    api_key: !secret darksky_password

shopping_list:

#group:      !include_dir_merge_named groups
automation: !include_dir_merge_list automations

panel_iframe:
  configurator:
    title: "configurator"
    url: "http://raspi2A:3218"

tuya:
  username: !secret tuya_id
  password: !secret tuya_password
  country_code: 1
  platform: smart_life

script:     !include_dir_merge_list scripts
sensor:     !include_dir_merge_list sensors
light:      !include_dir_merge_list lights
switch:     !include_dir_merge_list switches
camera:     !include cameras.yaml

#logger:
#  default: info  # critical, fatal,cerror, warning, warn, info, debug, notset
#  logs:
#    homeassistant.components.smartthings: debug

