- platform: mqtt
  name: "Spotlights"
  command_topic: "smartthings/Spotlights/switch"
  state_topic: "smartthings/Spotlights/switch"
  qos: 2
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "Virtual Switch 1"
  command_topic: "smartthings/Virtual Switch 1/switch"
  state_topic: "smartthings/Virtual Switch 1/switch"
  qos: 2
  payload_on: "on"
  payload_off: "off"
  retain: true

#- platform: mqtt
#  name: "Hallway"
#  command_topic: "smartthings/Hallway/switch"
#  state_topic: "smartthings/Hallway/switch"
#  qos: 2
#  payload_on: "on"
#  payload_off: "off"
#  retain: true

- platform: mqtt
  name: "Outlet(C) - Kitchen"
  command_topic: "smartthings/Outlet(C) - Kitchen/switch"
  state_topic: "smartthings/Outlet(C) - Kitchen/switch"
  qos: 2
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "Outlet(B) - ManCave Heater"
  command_topic: "smartthings/Outlet(B) - ManCave Heater/switch"
  state_topic: "smartthings/Outlet(B) - ManCave Heater/switch"
  qos: 2
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "Outlet(A) - Workshop"
  command_topic: "smartthings/Outlet(A) - Workshop/switch"
  state_topic: "smartthings/Outlet(A) - Workshop/switch"
  qos: 2
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "Aeon Labs Siren (Gen 5)"
  command_topic: "smartthings/Aeon Labs Siren (Gen 5)/switch"
  state_topic: "smartthings/Aeon Labs Siren (Gen 5)/switch"
  qos: 2
  payload_on: "on"
  payload_off: "off"
  retain: true
