- platform: mqtt
  name: "Entrance"
  command_topic: "smartthings/Entrance/switch"
  state_topic: "smartthings/Entrance/switch"
  brightness_command_topic: "smartthings/Entrance/level"
  brightness_state_topic: "smartthings/Entrance/level"
  qos: 2
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "Deck - Bedroom 1"
  command_topic: "smartthings/Deck - Bedroom 1/switch"
  state_topic: "smartthings/Deck - Bedroom 1/switch"
  brightness_command_topic: "smartthings/Deck - Bedroom 1/level"
  brightness_state_topic: "smartthings/Deck - Bedroom 1/level"
  qos: 2
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "Deck - Bedroom 2"
  command_topic: "smartthings/Deck - Bedroom 2/switch"
  state_topic: "smartthings/Deck - Bedroom 2/switch"
  brightness_command_topic: "smartthings/Deck - Bedroom 2/level"
  brightness_state_topic: "smartthings/Deck - Bedroom 2/level"
  qos: 2
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "Deck - Rear"
  command_topic: "smartthings/Deck - Rear/switch"
  state_topic: "smartthings/Deck - Rear/switch"
  brightness_command_topic: "smartthings/Deck - Rear/level"
  brightness_state_topic: "smartthings/Deck - Rear/level"
  qos: 2
  payload_on: "on"
  payload_off: "off"
  retain: true