- platform: mqtt
  name: "Spotlights"
  command_topic: "smartthings/Spotlights/switch"
  state_topic: "smartthings/Spotlights/switch"
  qos: 2
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "Outlet_C_Kitchen"
  command_topic: "smartthings/Outlet_C_Kitchen/switch"
  state_topic: "smartthings/Outlet_C_Kitchen/switch"
  qos: 2
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "Outlet_B_Rover"
  command_topic: "smartthings/Outlet_B_Rover/switch"
  state_topic: "smartthings/Outlet_B_Rover/switch"
  qos: 2
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "Outlet_A_Workshop"
  command_topic: "smartthings/Outlet_A_Workshop/switch"
  state_topic: "smartthings/Outlet_A_Workshop/switch"
  qos: 2
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "Aeon Labs Siren (Gen 5)"
  command_topic: "smartthings/Aeon Labs Siren (Gen 5)/switch"
  state_topic: "smartthings/Aeon Labs Siren (Gen 5)/switch"
  qos: 2
  payload_on: "on"
  payload_off: "off"
  retain: true