- platform: mqtt
  name: "tGreen"
  command_topic: "smartthings/tGreen/switch"
  state_topic: "smartthings/tGreen/switch"
  brightness_command_topic: "smartthings/tGreen/level"
  brightness_state_topic: "smartthings/tGreen/level"
  qos: 2
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "tGreen2"
  command_topic: "smartthings/tGreen2/switch"
  state_topic: "smartthings/tGreen2/switch"
  brightness_command_topic: "smartthings/tGreen2/level"
  brightness_state_topic: "smartthings/tGreen2/level"
  qos: 2
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "tRed"
  command_topic: "smartthings/tRed/switch"
  state_topic: "smartthings/tRed/switch"
  brightness_command_topic: "smartthings/tRed/level"
  brightness_state_topic: "smartthings/tRed/level"
  qos: 2
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "tRed2"
  command_topic: "smartthings/tRed2/switch"
  state_topic: "smartthings/tRed2/switch"
  brightness_command_topic: "smartthings/tRed2/level"
  brightness_state_topic: "smartthings/tRed2/level"
  qos: 2
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "tYellow"
  command_topic: "smartthings/tYellow/switch"
  state_topic: "smartthings/tYellow/switch"
  brightness_command_topic: "smartthings/tYellow/level"
  brightness_state_topic: "smartthings/tYellow/level"
  qos: 2
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "tYellow2"
  command_topic: "smartthings/tYellow2/switch"
  state_topic: "smartthings/tYellow2/switch"
  brightness_command_topic: "smartthings/tYellow2/level"
  brightness_state_topic: "smartthings/tYellow2/level"
  qos: 2
  payload_on: "on"
  payload_off: "off"
  retain: true
