- platform: mqtt
  name: "Spotlights"
  command_topic: "smartthings/Spotlights/switch"
  state_topic: "smartthings/Spotlights/switch"
  qos: 2
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "Sump"
  command_topic: "smartthings/Sump/switch"
  state_topic: "smartthings/Sump/switch"
  brightness_command_topic: "smartthings/Sump/level"
  brightness_state_topic: "smartthings/Sump/level"
  qos: 2
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "Utility-Room"
  command_topic: "smartthings/Utility-Room/switch"
  state_topic: "smartthings/Utility-Room/switch"
  brightness_command_topic: "smartthings/Utility-Room/level"
  brightness_state_topic: "smartthings/Utility-Room/level"
  qos: 2
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "Back-Stairway"
  command_topic: "smartthings/Back-Stairway/switch"
  state_topic: "smartthings/Back-Stairway/switch"
  brightness_command_topic: "smartthings/Back-Stairway/level"
  brightness_state_topic: "smartthings/Back-Stairway/level"
  qos: 2
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "Hutch Lamp"
  command_topic: "smartthings/Hutch Lamp/switch"
  state_topic: "smartthings/Hutch Lamp/switch"
  brightness_command_topic: "smartthings/Hutch Lamp/level"
  brightness_state_topic: "smartthings/Hutch Lamp/level"
  qos: 2
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "Stairway"
  command_topic: "smartthings/Stairway/switch"
  state_topic: "smartthings/Stairway/switch"
  brightness_command_topic: "smartthings/Stairway/level"
  brightness_state_topic: "smartthings/Stairway/level"
  qos: 2
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "Rear-Stairway"
  command_topic: "smartthings/Rear-Stairway/switch"
  state_topic: "smartthings/Rear-Stairway/switch"
  brightness_command_topic: "smartthings/Rear-Stairway/level"
  brightness_state_topic: "smartthings/Rear-Stairway/level"
  qos: 2
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "Hall"
  command_topic: "smartthings/Hall/switch"
  state_topic: "smartthings/Hall/switch"
  brightness_command_topic: "smartthings/Hall/level"
  brightness_state_topic: "smartthings/Hall/level"
  qos: 2
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "Bedroom"
  command_topic: "smartthings/Bedroom/switch"
  state_topic: "smartthings/Bedroom/switch"
  brightness_command_topic: "smartthings/Bedroom/level"
  brightness_state_topic: "smartthings/Bedroom/level"
  qos: 2
  payload_on: "on"
  payload_off: "off"
  retain: true
