# Sengled Essentials Plus bulbs

- platform: mqtt
  name: "Bar-1"
  command_topic: "smartthings/Bar-1/switch"
  state_topic: "smartthings/Bar-1/switch"
  brightness_command_topic: "smartthings/Bar-1/level"
  brightness_state_topic: "smartthings/Bar-1/level"
  color_temp_command_topic: "smartthings/Bar-1/colorTemperature"
  color_temp_state_topic:  "smartthings/Bar-1/colorTemperature"
  qos: 2
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "Bar-2"
  command_topic: "smartthings/Bar-2/switch"
  state_topic: "smartthings/Bar-2/switch"
  brightness_command_topic: "smartthings/Bar-2/level"
  brightness_state_topic: "smartthings/Bar-2/level"
  color_temp_command_topic: "smartthings/Bar-2/colorTemperature"
  color_temp_state_topic:  "smartthings/Bar-2/colorTemperature"
  qos: 2
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "Bar-3"
  command_topic: "smartthings/Bar-3/switch"
  state_topic: "smartthings/Bar-3/switch"
  brightness_command_topic: "smartthings/Bar-3/level"
  brightness_state_topic: "smartthings/Bar-3/level"
  color_temp_command_topic: "smartthings/Bar-3/colorTemperature"
  color_temp_state_topic:  "smartthings/Bar-3/colorTemperature"
  qos: 2
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "Bar-4"
  command_topic: "smartthings/Bar-4/switch"
  state_topic: "smartthings/Bar-4/switch"
  brightness_command_topic: "smartthings/Bar-4/level"
  brightness_state_topic: "smartthings/Bar-4/level"
  color_temp_command_topic: "smartthings/Bar-4/colorTemperature"
  color_temp_state_topic:  "smartthings/Bar-4/colorTemperature"
  qos: 2
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "Bar-5"
  command_topic: "smartthings/Bar-5/switch"
  state_topic: "smartthings/Bar-5/switch"
  brightness_command_topic: "smartthings/Bar-5/level"
  brightness_state_topic: "smartthings/Bar-5/level"
  color_temp_command_topic: "smartthings/Bar-5/colorTemperature"
  color_temp_state_topic:  "smartthings/Bar-5/colorTemperature"
  qos: 2
  payload_on: "on"
  payload_off: "off"
  retain: true  

- platform: mqtt
  name: "Bar-6"
  command_topic: "smartthings/Bar-6/switch"
  state_topic: "smartthings/Bar-6/switch"
  brightness_command_topic: "smartthings/Bar-6/level"
  brightness_state_topic: "smartthings/Bar-6/level"
  color_temp_command_topic: "smartthings/Bar-6/colorTemperature"
  color_temp_state_topic:  "smartthings/Bar-6/colorTemperature"
  qos: 2
  payload_on: "on"
  payload_off: "off"
  retain: true  

- platform: mqtt
  name: "Hall-1"
  command_topic: "smartthings/Hall-1/switch"
  state_topic: "smartthings/Hall-1/switch"
  brightness_command_topic: "smartthings/Hall-1/level"
  brightness_state_topic: "smartthings/Hall-1/level"
  color_temp_command_topic: "smartthings/Hall-1/colorTemperature"
  color_temp_state_topic:  "smartthings/Hall-1/colorTemperature"
  qos: 2
  payload_on: "on"
  payload_off: "off"
  retain: true  

- platform: mqtt
  name: "Hall-2"
  command_topic: "smartthings/Hall-2/switch"
  state_topic: "smartthings/Hall-2/switch"
  brightness_command_topic: "smartthings/Hall-2/level"
  brightness_state_topic: "smartthings/Hall-2/level"
  color_temp_command_topic: "smartthings/Hall-2/colorTemperature"
  color_temp_state_topic:  "smartthings/Hall-2/colorTemperature"
  qos: 2
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "Hall-3"
  command_topic: "smartthings/Hall-3/switch"
  state_topic: "smartthings/Hall-3/switch"
  brightness_command_topic: "smartthings/Hall-3/level"
  brightness_state_topic: "smartthings/Hall-3/level"
  color_temp_command_topic: "smartthings/Hall-3/colorTemperature"
  color_temp_state_topic:  "smartthings/Hall-3/colorTemperature"
  qos: 2
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "Hall-4"
  command_topic: "smartthings/Hall-4/switch"
  state_topic: "smartthings/Hall-4/switch"
  brightness_command_topic: "smartthings/Hall-4/level"
  brightness_state_topic: "smartthings/Hall-4/level"
  color_temp_command_topic: "smartthings/Hall-4/colorTemperature"
  color_temp_state_topic:  "smartthings/Hall-4/colorTemperature"
  qos: 2
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "Table"
  command_topic: "smartthings/Table/switch"
  state_topic: "smartthings/Table/switch"
  brightness_command_topic: "smartthings/Table/level"
  brightness_state_topic: "smartthings/Table/level"
  color_temp_command_topic: "smartthings/Table/colorTemperature"
  color_temp_state_topic:  "smartthings/Table/colorTemperature"
  qos: 2
  payload_on: "on"
  payload_off: "off"
  retain: true
